@ECHO OFF
python --version
pip install -r requirements.txt
python setup.py install
pip install webdriver_manager
pip install packaging
pip install setuptool
pip install setuptools-scm
pip install wheel
pip install six
pip install nose
pip install ipdb
pip install parso
pip install jedi
pip install idna
pip install chardet
pip install urllib3
pip install requests
pip install selenium
pip install msedge-selenium-tools
pip install more-itertools
pip install cssselect
pip install pluggy
pip install attrs
pip install pytest
pip install pytest-cov
pip install pytest-forked
pip install pytest-metadata
pip install pytest-ordering
pip install pytest-rerunfailures
pip install pytest-xdist
pip install parameterized
pip install soupsieve
pip install beautifulsoup4
pip install cryptography
pip install pyopenssl
pip install pygments
pip install traitlets
pip install prompt-toolkit
pip install ipython
pip install colorama
pip install pip install importlib-metadata
pip install virtualenv
pip install pymysql
pip install coverage
pip install brython
pip install pyotp
pip install boto
pip install cffi
pip install rich
pip install zipp
pip install flake8
pip install pyflakes
pip install tornado
pip install certifi
pip install allure-pytest
pip install pdfminer.six
pip install pytest-json-report
pip install pytest-json
pip install pytest-html-reporter
pip install pytest-bdd
pip install pytest-html
pip install pytest-bdd
pip install pytest-bdd-web
pip install pytest-metadata
pip install pytest-ordering
