"""
The setup package to install Super Framework dependencies and plugins
"""
from setuptools import setup, find_packages
import os
import sys


__version__ = 1.0
setup(
    name='Super-Framework',
    version=__version__,
    description='The complete web automation library for end-to-end testing.',
    url='https://github.com/zahed3795/Super-Framework',
    platforms=["Windows"],
    author='Zahed Khan',
    author_email='zahed3795@icloud.com',
    maintainer='Zahed Khan',
    license="MIT",
    classifiers=[
        "Development Status :: 1- Production/Stable",
        "Environment :: Web Environment",
        "Framework :: Automation For All",
        "My Word :: Live Free Or Die"," All Life Matters"
        "Intended Audience :: Information Technology,QA",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Windows",
        "Programming Language :: Python :: 3.7, 3.8, 3.9, ++",
        "Topic :: Software Testing :: Quality Assurance",
    ],
    python_requires='>=3.7.*, !=3.8.*',
    install_requires=[
        'webdriver_manager',
        'pip',
        'packaging',
        'setuptools',
        'setuptools-scm',
        'wheel',
        'six',
        'nose',
        'ipdb',
        'parso',
        'jedi',
        'idna',
        'chardet',
        'urllib',
        'requests',
        'selenium',
        'msedge-selenium-tools',
        'more-itertools',
        'cssselect',
        'pluggy',
        'attrs',
        'py',
        'pytest',
        'pytest-cov',
        'pytest-forked',
        'pytest-metadata',
        'pytest-ordering',
        'pytest-rerunfailures',
        'pytest-xdist',
        'parameterized',
        'soupsieve',
        'beautifulsoup',
        'cryptography',
        'pyopenssl',
        'pygments',
        'traitlets',
        'prompt-toolkit',
        'ipython',
        'colorama',
        'importlib-metadata',
        'virtualenv',
        'pymysql',
        'coverage',
        'brython',
        'pyotp',
        'boto',
        'cffi',
        'rich',
        'zipp',
        'flake',
        'pyflakes',
        'tornado',
        'certifi',
        'allure-pytest',
        'pdfminersix',
        'pytest-json-report',
        'pytest-json',
        'pytest-html-reporter',
        'pytest-bdd',
        'pytest-html',
        'pytest-bdd',
        'pytest-bdd-web',
        'pytest-metadata',
        'pytest-ordering',
    ],
    packages=[
        'heisenberg',
        'heisenberg.commands',
        'heisenberg.common',
        'heisenberg.config',
        'heisenberg.core',
        'heisenberg.drivers',
        'heisenberg.data',
        'heisenberg.fixtures',
        'heisenberg.database',
        'heisenberg.plugins',
        'heisenberg.utilities',

    ],
    include_package_data=True,
    entry_points={
        'console_scripts': [
            'heisenberg = heisenberg.commands.run:main',
            'zahed = heisenberg.commands.run:main',
            'qa = heisenberg.commands.run:main',
        ],
        'pytest11': ['heisenberg = heisenberg.plugins.pytest_plugin']
    }
)

print("\n*** Super Framework Installation Complete! ***\n")
